CREATE TABLE ORA_IND_COLUMNS
 (
   BIZ_AREA_ID              VARCHAR2(10),
   TRGT_ID                  VARCHAR2(10),
   INDEX_NAME       		VARCHAR2(30) NOT NULL,
   TABLE_NAME       		VARCHAR2(30) NOT NULL,
   COLUMN_NAME              VARCHAR2(4000),
   COLUMN_POSITION  		NUMBER NOT NULL,
   DESCEND                  VARCHAR2(4)
 );