CREATE TABLE ORA_CONS_COLUMNS
  (
    BIZ_AREA_ID     VARCHAR2(10),
    TRGT_ID         VARCHAR2(10),
    CONSTRAINT_NAME VARCHAR2(30) NOT NULL,
    TABLE_NAME      VARCHAR2(30) NOT NULL,
    COLUMN_NAME     VARCHAR2(4000),
    POSITION        NUMBER
  );