CREATE TABLE ora_sqlstats (
  jb_id                          varchar2(32) NOT NULL,
  biz_area_id                    varchar2(32) NOT NULL,
  trgt_id                        varchar2(32) NOT NULL,
  jb_exec_cnt                    number       NOT NULL,
  sql_text                       varchar2(2000),
  sql_id                         varchar2(13),
  last_active_time               date,
  last_active_child_address      raw(8),
  plan_hash_value                number,
  parse_calls                    number,
  disk_reads                     number,
  direct_writes                  number,
  buffer_gets                    number,
  rows_processed                 number,
  serializable_aborts            number,
  fetches                        number,
  executions                     number,
  end_of_fetch_count             number,
  loads                          number,
  version_count                  number,
  invalidations                  number,
  px_servers_executions          number,
  cpu_time                       number,
  elapsed_time                   number,
  avg_hard_parse_time            number,
  application_wait_time          number,
  concurrency_wait_time          number,
  cluster_wait_time              number,
  user_io_wait_time              number,
  plsql_exec_time                number,
  java_exec_time                 number,
  sorts                          number,
  sharable_mem                   number,
  total_sharable_mem             number,
  typecheck_mem                  number,
  io_cell_offload_eligible_bytes number,
  io_interconnect_bytes          number,
  physical_read_requests         number,
  physical_read_bytes            number,
  physical_write_requests        number,
  physical_write_bytes           number,
  exact_matching_signature       number,
  force_matching_signature       number,
  io_cell_uncompressed_bytes     number,
  io_cell_offload_returned_bytes number
);