CREATE TABLE ORA_TAB_SUBPARTITIONS
(
  JB_ID                 VARCHAR2(32) NOT NULL,
  BIZ_AREA_ID           VARCHAR2(32) NOT NULL,
  TRGT_ID               VARCHAR2(32) NOT NULL,
  JB_EXEC_CNT           NUMBER       NOT NULL,
  TABLE_NAME            VARCHAR2(30) NOT NULL,
  PARTITION_NAME        VARCHAR2(30),
  SUBPARTITIONS_NAME    VARCHAR2(30),
  HIGH_VALUE            LONG,
  SUBPARTITION_POSITION NUMBER,
  TABLESPACE_NAME       VARCHAR2(30) NOT NULL,
  NUM_ROWS              NUMBER,
  BLOCKS                NUMBER,
  SAMPLE_SIZE           NUMBER
);