CREATE TABLE ORA_IND_COLUMNS
(
  JB_ID           VARCHAR2(32) NOT NULL,
  BIZ_AREA_ID     VARCHAR2(32) NOT NULL,
  TRGT_ID         VARCHAR2(32) NOT NULL,
  JB_EXEC_CNT     NUMBER       NOT NULL,
  INDEX_NAME      VARCHAR2(30) NOT NULL,
  TABLE_NAME      VARCHAR2(30) NOT NULL,
  COLUMN_NAME     VARCHAR2(4000),
  COLUMN_POSITION NUMBER       NOT NULL,
  DESCEND         VARCHAR2(4)
);