CREATE TABLE ORA_CONS_COLUMNS
(
  JB_ID           VARCHAR2(32) NOT NULL,
  BIZ_AREA_ID     VARCHAR2(32) NOT NULL,
  TRGT_ID         VARCHAR2(32) NOT NULL,
  JB_EXEC_CNT     NUMBER       NOT NULL,
  CONSTRAINT_NAME VARCHAR2(30) NOT NULL,
  TABLE_NAME      VARCHAR2(30) NOT NULL,
  COLUMN_NAME     VARCHAR2(4000),
  POSITION        NUMBER
);