-- 업무 영역 테이블

CREATE TABLE BIZ_AREA
(
  BIZ_AREA_ID     VARCHAR2(32)  NOT NULL, -- 업무영역 아이디
  BIZ_AREA_NM     VARCHAR2(50)  NOT NULL, -- 업무영역 명칭
  BIZ_AREA_DESCR  VARCHAR2(100) NOT NULL, -- 업무영역 설명
  BIZ_AREA_ST_TM  VARCHAR2(32)  NOT NULL, -- 업무영역 등록 일시
  BIZ_AREA_UPT_TM VARCHAR2(32) -- 업무영역 변경 일시
);

ALTER TABLE BIZ_AREA ADD CONSTRAINT BIZ_AREA_PK PRIMARY KEY (BIZ_AREA_ID);

INSERT INTO BIZ_AREA VALUES (sys_guid(), 'Biz Area No 1', 'This Bizarea is created for test', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);
INSERT INTO BIZ_AREA VALUES (sys_guid(), 'Biz Area No 2', '한글 테스트', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);
COMMIT;