CREATE TABLE DBMS_TYP(
  DBMS_TYP_ID VARCHAR2(10),
  DBMS_TYP_NM VARCHAR2(20),
  DBMS_VER VARCHAR2(20),
  DBMS_DRIVER VARCHAR2(50)
);

ALTER TABLE DBMS_TYP ADD CONSTRAINT DBMS_TYP_PK PRIMARY KEY (DBMS_TYP_ID);

CREATE TABLE DBMS_TYP_PER_CLCT_TAB(
  DBMS_TYP_ID VARCHAR2(10),
  SEQ VARCHAR2(4),
  CLCT_TAB_NM VARCHAR2(30),
  EXPORT_SQL VARCHAR2(2000),
  IMPORT_SQL VARCHAR2(2000)
);

ALTER TABLE DBMS_TYP_PER_CLCT_TAB ADD CONSTRAINT DBMS_TYP_PER_CLCT_TAB_FK FOREIGN KEY (DBMS_TYP_ID) REFERENCES DBMS_TYP(DBMS_TYP_ID);
ALTER TABLE DBMS_TYP_PER_CLCT_TAB ADD CONSTRAINT DBMS_TYP_PER_CLCT_TAB_PK PRIMARY KEY (DBMS_TYP_ID, SEQ);

INSERT INTO DBMS_TYP VALUES ('DBMS0001', 'ORACLE RDBMS', '11G R2', 'oracle.jdbc.driver.OracleDriver');
INSERT INTO DBMS_TYP VALUES ('DBMS0002', 'ORACLE RDBMS', '10G R1', NULL);

INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '01', 'DBA_TABLES', 'SELECT TABLE_NAME, TABLESPACE_NAME, NUM_ROWS, BLOCKS, EMPTY_BLOCKS, AVG_SPACE, CHAIN_CNT, AVG_ROW_LEN, AVG_SPACE_FREELIST_BLOCKS, SAMPLE_SIZE, PARTITIONED, TEMPORARY FROM DBA_TABLES WHERE OWNER = ?','INSERT INTO ORA_TABLES VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '02', 'DBA_TAB_COLUMNS', 'SELECT TABLE_NAME, COLUMN_NAME, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DATA_DEFAULT, NUM_DISTINCT, LOW_VALUE, HIGH_VALUE, DENSITY, NUM_NULLS, NUM_BUCKETS, SAMPLE_SIZE  FROM DBA_TAB_COLUMNS WHERE OWNER = ?','INSERT INTO ORA_TAB_COLUMNS VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '03', 'DBA_CONSTRAINTS', 'SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION, R_OWNER, R_CONSTRAINT_NAME, DELETE_RULE, STATUS , INDEX_OWNER, INDEX_NAME FROM DBA_CONSTRAINTS WHERE OWNER = ?','INSERT INTO ORA_CONSTRAINTS VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');
INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '04', 'DBA_CONS_COLUMNS', 'SELECT CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME, POSITION FROM DBA_CONS_COLUMNS WHERE OWNER = ?','INSERT INTO ORA_CONS_COLUMNS VALUES(?,?,?,?,?,?)');
INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '05', 'DBA_INDEXES', 'SELECT INDEX_NAME, INDEX_TYPE, TABLE_NAME, UNIQUENESS, TABLESPACE_NAME, BLEVEL, LEAF_BLOCKS, DISTINCT_KEYS, AVG_LEAF_BLOCKS_PER_KEY, AVG_DATA_BLOCKS_PER_KEY, CLUSTERING_FACTOR, NUM_ROWS, SAMPLE_SIZE, PARTITIONED FROM DBA_INDEXES WHERE OWNER = ?','INSERT INTO ORA_INDEXES VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '06', 'DBA_IND_PARTITIONS', 'SELECT INDEX_NAME, COMPOSITE, PARTITION_NAME, HIGH_VALUE, PARTITION_POSITION, TABLESPACE_NAME, BLEVEL, LEAF_BLOCKS, DISTINCT_KEYS, AVG_LEAF_BLOCKS_PER_KEY, AVG_DATA_BLOCKS_PER_KEY, CLUSTERING_FACTOR, NUM_ROWS, SAMPLE_SIZE FROM DBA_IND_PARTITIONS WHERE INDEX_OWNER = ?','INSERT INTO ORA_IND_PARTITIONS VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '07', 'DBA_IND_SUBPARTITIONS', 'SELECT INDEX_NAME, PARTITION_NAME, SUBPARTITION_NAME, HIGH_VALUE, SUBPARTITION_POSITION, TABLESPACE_NAME, BLEVEL, LEAF_BLOCKS, DISTINCT_KEYS, AVG_LEAF_BLOCKS_PER_KEY, AVG_DATA_BLOCKS_PER_KEY, CLUSTERING_FACTOR, NUM_ROWS, SAMPLE_SIZE FROM DBA_IND_SUBPARTITIONS WHERE INDEX_OWNER = ?','INSERT INTO ORA_IND_SUBPARTITIONS VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '08', 'DBA_IND_COLUMNS', 'SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME, COLUMN_POSITION, DESCEND FROM DBA_IND_COLUMNS WHERE TABLE_OWNER = ?','INSERT INTO ORA_IND_COLUMNS VALUES(?,?,?,?,?,?,?)');
INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '09', 'DBA_TAB_PARTITIONS', 'SELECT TABLE_NAME, COMPOSITE, PARTITION_NAME, HIGH_VALUE, PARTITION_POSITION, TABLESPACE_NAME, NUM_ROWS, BLOCKS, SAMPLE_SIZE FROM DBA_TAB_PARTITIONS WHERE TABLE_OWNER = ?','INSERT INTO ORA_TAB_PARTITIONS VALUES(?,?,?,?,?,?,?,?,?,?,?)');
INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '10', 'DBA_TAB_SUBPARTITIONS', 'SELECT TABLE_NAME, PARTITION_NAME, SUBPARTITION_NAME, HIGH_VALUE, SUBPARTITION_POSITION, TABLESPACE_NAME, NUM_ROWS, BLOCKS, SAMPLE_SIZE FROM DBA_TAB_SUBPARTITIONS WHERE TABLE_OWNER = ?','INSERT INTO ORA_TAB_SUBPARTITIONS VALUES(?,?,?,?,?,?,?,?,?,?,?)');
INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '11', 'DBA_SEQUENCES', 'SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG, ORDER_FLAG, CACHE_SIZE, LAST_NUMBER FROM DBA_SEQUENCES WHERE SEQUENCE_OWNER = ?','INSERT INTO ORA_SEQUENCES VALUES(?,?,?,?,?,?,?,?,?,?)');

COMMIT;

