CREATE TABLE DBMS_TYP(
  DBMS_TYP_ID VARCHAR2(10),
  DBMS_TYP_NM VARCHAR2(20),
  DBMS_VER VARCHAR2(20)
);

ALTER TABLE DBMS_TYP ADD CONSTRAINT DBMS_TYP_PK PRIMARY KEY (DBMS_TYP_ID);

CREATE TABLE DBMS_TYP_PER_CLCT_TAB(
  DBMS_TYP_ID VARCHAR2(10),
  SEQ VARCHAR2(4),
  CLCT_TAB_NM VARCHAR2(20),
  EXPORT_SQL VARCHAR2(2000),
  IMPORT_SQL VARCHAR2(2000)
);

ALTER TABLE DBMS_TYP_PER_CLCT_TAB ADD CONSTRAINT DBMS_TYP_PER_CLCT_TAB_FK FOREIGN KEY (DBMS_TYP_ID) REFERENCES DBMS_TYP(DBMS_TYP_ID);
ALTER TABLE DBMS_TYP_PER_CLCT_TAB ADD CONSTRAINT DBMS_TYP_PER_CLCT_TAB_PK PRIMARY KEY (DBMS_TYP_ID, SEQ);

INSERT INTO DBMS_TYP VALUES ('DBMS0001', 'ORACLE RDBMS', '11G R2');
INSERT INTO DBMS_TYP VALUES ('DBMS0002', 'ORACLE RDBMS', '10G R1');

INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '1', 'DBA_TABLES', 'SELECT TABLE_NAME, TABLESPACE_NAME, NUM_ROWS, BLOCKS, EMPTY_BLOCKS, AVG_SPACE, CHAIN_CNT, AVG_ROW_LEN, AVG_SPACE_FREELIST_BLOCKS, SAMPLE_SIZE, PARTITIONED, TEMPORARY FROM DBA_TABLES WHERE OWNER = ?','INSERT INTO REP_TABLES VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');
INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '2', 'DBA_TAB_COLS', 'SELECT TABLE_NAME, COLUMN_NAME, COLUMN_ID, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, NUM_DISTINCT, DENSITY, NUM_NULLS, NUM_BUCKETS, SAMPLE_SIZE FROM DBA_TAB_COLUMNS WHERE OWNER = ?', 'INSERT INTO REP_TABL_COLS VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');

COMMIT;