CREATE TABLE JB_EXEC_DTL
(
  JB_ID VARCHAR2(32),
  BIZ_AREA_ID VARCHAR2(32) NOT NULL,
  TRGT_ID     VARCHAR2(32) NOT NULL,
  JB_EXEC_CNT NUMBER NOT NULL,
  JB_EXEC_ITM_ID VARCHAR2(32) NOT NULL,
  JB_ITM_EXEC_ED_TM VARCHAR2(32) NOT NULL,
  JB_ITM_EXEC_ST_TM VARCHAR2(32) NOT NULL
);


ALTER TABLE JB_EXEC_DTL ADD CONSTRAINT JB_EXEC_DTL_PK PRIMARY KEY (JB_ID, BIZ_AREA_ID, TRGT_ID, JB_EXEC_CNT, JB_EXEC_ITM_ID);