CREATE TABLE JB
(
  JB_ID VARCHAR2(32) NOT NULL,
  JB_NM VARCHAR2(50) NOT NULL,
  JB_TYP VARCHAR2(2) NOT NULL,
  JB_ST_TM VARCHAR2(32) NOT NULL,
  JB_UPT_TM VARCHAR2(32)
);

ALTER TABLE JB ADD CONSTRAINT JB_PK PRIMARY KEY (JB_ID);

INSERT INTO JB VALUES (SYS_GUID(), '수집 작업 1', '01', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);
INSERT INTO JB VALUES (SYS_GUID(), '수집 작업 2', '01', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);
INSERT INTO JB VALUES (SYS_GUID(), '수집 작업 3', '01', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);
INSERT INTO JB VALUES (SYS_GUID(), '수집 작업 4', '01', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);


INSERT INTO JB VALUES (SYS_GUID(), '검사 작업 1', '02', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);
INSERT INTO JB VALUES (SYS_GUID(), '검사 작업 2', '02', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);
INSERT INTO JB VALUES (SYS_GUID(), '검사 작업 3', '02', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);
INSERT INTO JB VALUES (SYS_GUID(), '검사 작업 4', '02', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);





