CREATE TABLE JB_TRGT_REL
(
  JB_ID       VARCHAR2(32) NOT NULL,
  BIZ_AREA_ID VARCHAR2(32) NOT NULL, -- 업무영역 아이디
  TRGT_ID     VARCHAR2(32) NOT NULL,  -- 대상 아이디
  EXEC_SEQ    NUMBER       NOT NULL
);

ALTER TABLE JB_TRGT_REL ADD CONSTRAINT JB_TRGT_REL_PK PRIMARY KEY (JB_ID, BIZ_AREA_ID, TRGT_ID);

INSERT INTO JB_TRGT_REL
  SELECT
    (SELECT *
     FROM (
       SELECT JB_ID
       FROM JB
       ORDER BY DBMS_RANDOM.VALUE())
     WHERE ROWNUM <= 1),
    ROWNUM,
    BIZ_AREA_ID,
    TRGT_ID
  FROM (
    SELECT
      BIZ_AREA_ID,
      TRGT_ID
    FROM TRGT
    ORDER BY DBMS_RANDOM.VALUE())
  WHERE ROWNUM <= 3;

COMMIT;