CREATE TABLE TRGT
(
  BIZ_AREA_ID VARCHAR2(32) NOT NULL, -- 업무영역 아이디
  TRGT_ID     VARCHAR2(32) NOT NULL, -- 대상 아이디
  TRGT_NM     VARCHAR2(50) NOT NULL, -- 대상 명칭
  TRGT_TYP    VARCHAR2(20) NOT NULL, -- 대상 유형
  IP          VARCHAR2(50), -- 대상 IP
  PRT         VARCHAR2(50), -- 대상 포트
  DBMS_TYP_ID VARCHAR2(10), -- 대상 디비 유형 아이디
  USR_ID      VARCHAR2(10), -- 대상 디비 사용자 아이디
  PW          VARCHAR2(20), -- 대상 디비 사용자 비밀번호
  SID         VARCHAR2(20), -- 대상 디비 서버 아이디
  SCHM        VARCHAR2(20), -- 대상 스키마 명칭
  TRGT_ST_TM  VARCHAR2(32) NOT NULL, -- 대상 등록 일시
  TRGT_UPT_TM VARCHAR2(32) -- 대상 변경 일시
);

ALTER TABLE TRGT ADD CONSTRAINT TRGT_PK PRIMARY KEY (BIZ_AREA_ID, TRGT_ID);

INSERT INTO TRGT (BIZ_AREA_ID, TRGT_ID, TRGT_NM, TRGT_TYP, IP, PRT, DBMS_TYP_ID, USR_ID, PW, SID, SCHM, TRGT_ST_TM, TRGT_UPT_TM)
VALUES ((SELECT BIZ_AREA_ID
         FROM BIZ_AREA
         WHERE ROWNUM <= 1), SYS_GUID(), 'DBECRDB1',
        '01',
        '210.110.136.101', '1521', 'DBMS0001', 'SCOTT', 'TIGER', 'DBECRDB', 'SCOTT', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);


INSERT INTO TRGT (BIZ_AREA_ID, TRGT_ID, TRGT_NM, TRGT_TYP, IP, PRT, DBMS_TYP_ID, USR_ID, PW, SID, SCHM, TRGT_ST_TM, TRGT_UPT_TM)
VALUES ((SELECT BIZ_AREA_ID
         FROM BIZ_AREA
         WHERE ROWNUM <= 1), SYS_GUID(), 'DBECRDB1',
        '01',
        '210.110.136.102', '1521', 'DBMS0002', 'SCOTT', 'TIGER', 'DBECRDB', 'SCOTT', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);

INSERT INTO TRGT (BIZ_AREA_ID, TRGT_ID, TRGT_NM, TRGT_TYP, IP, PRT, DBMS_TYP_ID, USR_ID, PW, SID, SCHM, TRGT_ST_TM, TRGT_UPT_TM)
VALUES ((SELECT BIZ_AREA_ID
         FROM BIZ_AREA
         WHERE ROWNUM <= 1), SYS_GUID(), 'DBECRDB1',
        '01',
        '210.110.136.103', '1521', 'DBMS0003', 'SCOTT', 'TIGER', 'DBECRDB', 'SCOTT', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);

INSERT INTO TRGT (BIZ_AREA_ID, TRGT_ID, TRGT_NM, TRGT_TYP, IP, PRT, DBMS_TYP_ID, USR_ID, PW, SID, SCHM, TRGT_ST_TM, TRGT_UPT_TM)
VALUES ((SELECT BIZ_AREA_ID
         FROM BIZ_AREA
         WHERE ROWNUM <= 1), SYS_GUID(), 'DBECRDB1',
        '01',
        '210.110.136.104', '1521', 'DBMS0004', 'SCOTT', 'TIGER', 'DBECRDB', 'SCOTT', TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), NULL);
