CREATE TABLE BIZ_AREA
(
  biz_area_id    VARCHAR2(10)  NOT NULL,
  biz_area_nm    VARCHAR2(20)  NOT NULL,
  biz_area_descr VARCHAR2(100) NOT NULL
);


INSERT INTO BIZ_AREA VALUES ('BIZ0001', 'Biz Area No 1', 'This Bizarea is created for test');


SELECT
  biz_area_id    AS bizAreaId,
  biz_area_nm    AS bizAreaNm,
  biz_area_descr AS bizAreaDescr
FROM BIZ_AREA;



CREATE SEQUENCE BIZ_AREA_SEQ
INCREMENT BY 1
START WITH 1
MAXVALUE 9999;



CREATE TABLE TRGT
(
  biz_area_id     VARCHAR2(10)  NOT NULL,
  trgt_id     VARCHAR2(10)  NOT NULL,
  trgt_nm     VARCHAR2(20)  NOT NULL,
  trgt_typ     VARCHAR2(20)  NOT NULL,
  ip	 VARCHAR2(50),
  prt	 VARCHAR2(50),
  dbms_typ	 VARCHAR2(20),
  usr_id	 VARCHAR2(10),
  pw	 VARCHAR2(20),
  serv	 VARCHAR2(20),
  schm	 VARCHAR2(20),
  dbms_typ_num	 NUMBER(10),
  pth	 VARCHAR2(50),
  clct_cycl	 NUMBER(20)
);

INSERT INTO TRGT(biz_area_id, trgt_id, trgt_nm, trgt_typ, ip, prt, usr_id, pw, serv, schm, dbms_typ_id) VALUES ('BIZ0001','TRGT0001','DBECRDB1','01','210.110.136.101','1521','SCOTT','TIGER','','SCOTT','DBMS0001');
INSERT INTO TRGT(biz_area_id, trgt_id, trgt_nm, trgt_typ, ip, prt, usr_id, pw, serv, schm, dbms_typ_id) VALUES ('BIZ0001','TRGT0002','DBECRDB2','01','210.110.136.102','1521','SCOTT','TIGER','','SCOTT','DBMS0001');
INSERT INTO TRGT(biz_area_id, trgt_id, trgt_nm, trgt_typ, ip, prt, usr_id, pw, serv, schm, dbms_typ_id) VALUES ('BIZ0001','TRGT0003','DBECRDB3','01','210.110.136.103','1521','SCOTT','TIGER','','SCOTT','DBMS0001');
INSERT INTO TRGT(biz_area_id, trgt_id, trgt_nm, trgt_typ, ip, prt, usr_id, pw, serv, schm, dbms_typ_id) VALUES ('BIZ0001','TRGT0004','DBECRDB4','01','210.110.136.104','1521','SCOTT','TIGER','','SCOTT','DBMS0001');

CREATE TABLE DBMS_TYP(
  DBMS_TYP_ID VARCHAR2(10),
  DBMS_TYP_NM VARCHAR2(20),
  DBMS_VER VARCHAR2(20)
);

CREATE TABLE DBMS_TYP_PER_CLCT_TAB(
  DBMS_TYP_ID VARCHAR2(10),
  SEQ VARCHAR2(4),
  CLCT_TAB_NM VARCHAR2(20),
  EXPORT_SQL VARCHAR2(2000),
  IMPORT_SQL VARCHAR2(2000)
);

INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '1', 'DBA_TABLES', 'SELECT TABLE_NAME, TABLESPACE_NAME, NUM_ROWS, BLOCKS, EMPTY_BLOCKS, AVG_SPACE, CHAIN_CNT, AVG_ROW_LEN, AVG_SPACE_FREELIST_BLOCKS, SAMPLE_SIZE, PARTITIONED, TEMPORARY FROM DBA_TABLES WHERE OWNER = ?','INSERT INTO REP_TABLES VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');
INSERT INTO DBMS_TYP_PER_CLCT_TAB VALUES('DBMS0001', '2', 'DBA_TAB_COLS', 'SELECT TABLE_NAME, COLUMN_NAME, COLUMN_ID, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, NUM_DISTINCT, DENSITY, NUM_NULLS, NUM_BUCKETS, SAMPLE_SIZE FROM DBA_TAB_COLUMNS WHERE OWNER = ?', 'INSERT INTO REP_TABL_COLS VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');

CREATE TABLE REP_TABLES(
  BIZ_AREA_ID VARCHAR2(10),
  TRGT_ID VARCHAR2(10),
  TAB_NM	 VARCHAR2(20)  NOT NULL ,
  TAB_SPC_NM	 VARCHAR2(20)  NOT NULL ,
  RW_NUM	 NUMBER(10)  NOT NULL ,
  BLK_QTY	 NUMBER(8)  NOT NULL ,
  FR_BLK_QTY	 NUMBER(8)  NOT NULL ,
  AVG_SPC	 NUMBER(10)  NOT NULL ,
  CHN_QTY	 NUMBER(8)  NOT NULL ,
  RW_AVG_LEN	 NUMBER(6)  NOT NULL ,
  SPC_AVG_FRL_BLK_QTY	 NUMBER(8)  NOT NULL ,
  SAMP_SZ	 NUMBER(10)  NOT NULL ,
  PART_WON	 VARCHAR2 (3 BYTE)  NOT NULL ,
  TMP_TAB_WON	VARCHAR2 (3 BYTE)  NOT NULL
);

CREATE TABLE REP_TAB_COLS
(
  BIZ_AREA_ID VARCHAR2(10),
  TRGT_ID VARCHAR2(10),
  TAB_NM	 VARCHAR2(20)  NOT NULL ,
  COL_NM	 VARCHAR2(20)  NOT NULL ,
  COL_ID	 VARCHAR2(10)  NOT NULL ,
  DATA_LEN	 NUMBER(6)  NOT NULL ,
  DEC_ACRCY	 NUMBER(10,4)  NOT NULL ,
  DEC_PNT_RT_DGT_QTY	 NUMBER(8)  NOT NULL ,
  NUL_VAL_USE_WON	 CHAR(1)  NOT NULL ,
  DFLT_VAL	 NUMBER(20)  NOT NULL ,
  VAL_VAR_TYP	 VARCHAR2(20)  NOT NULL ,
  NIN_VAL	 NUMBER(20)  NOT NULL ,
  MAX_VAL	 NUMBER(20)  NOT NULL ,
  DNS	 NUMBER(20,19)  NOT NULL ,
  NUL_QTY	 NUMBER(8)  NOT NULL ,
  BCKT_QTY	 NUMBER(8)  NOT NULL ,
  SAMP_SZ	 NUMBER(10)  NOT NULL
);